[package]
name = "corroscope"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
bevy = { version = "^0.11.0", default_features = false, features = [
    #"bevy_asset",
    "bevy_core_pipeline",
    "bevy_render",
    #"bevy_scene",
    #"bevy_sprite",
    #"bevy_text",
    #"subpixel_glyph_atlas",
    "bevy_winit",
    # "bevy_dynamic_plugin",
    "wayland",
    "x11",
    "multi-threaded"
    ] }
bevy_prototype_lyon = "^0.9.0"
bevy_egui = { version = "^0.21.0", default_features = false, features = [ "manage_clipboard" ] }
bevy_pancam = { version = "0.9", features = [ "bevy_egui" ] }
bevy_mod_picking = { git = "https://github.com/Vrixyz/bevy_mod_picking", branch = "bevy-0.11-compatibility", default_features = false, features = [
    # "backend_egui",
    "backend_raycast",
    "selection",
    ] }

bevy_eventlistener = { git = "https://github.com/aevyrie/bevy_eventlistener.git", branch = "main" }

bevy_framepace = "0.13.3"

bevy-inspector-egui = { version = "0.19.0", optional = false, default_features = false }
bevy_editor_pls = { git = "https://github.com/jakobhellermann/bevy_editor_pls.git", branch = "main", optional = true }

bevy_mod_debugdump = { version = "0.8.0", optional = true }

egui = { version = "0.22.0", features = [
    "mint",
    "extra_debug_asserts"
    ] }

mint = "^0.5.9"

lyon_algorithms = "^1"
lyon_path = "^1"

color-eyre = { version = "0.5", default-features = false }

bytes = "1"
prost = "0.11.8"

# Not yet used
# petgraph = "0.6.3"

glam = "0.24.1"

csv = "1.2"
serde = "1.0"
serde_json = "1.0"

clap = { version = "4.3.19", features = ["derive"] }
itertools = "0.11.0"
memmap2 = "0.7.1"
futures-lite = "1.13.0"
thingbuf = "0.1.4"
egui_extras = "0.22.0"

# bevy_picking_egui = { git = "https://github.com/Vrixyz/bevy_mod_picking", branch = "bevy-0.11-compatibility", package = "bevy_picking_egui", default_features = false }

#[patch."https://github.com/Vrixyz/bevy_mod_picking"]
#bevy_egui = { version = "^0.21.0"  }

[patch.crates-io]
bevy_mod_raycast = { git = "https://github.com/Vrixyz/bevy_mod_raycast.git", branch = "bevy-0.11-compatibility" }

[build-dependencies]
prost-build = "0.11.8"

[features]
default = []
dynamic_linking = ["bevy/dynamic_linking"]
export_schedule = ["bevy_mod_debugdump"]
debug_picking = ["bevy_mod_picking/debug"]
editor = ["bevy_editor_pls"]
dev = ["dynamic_linking", "editor", "export_schedule"]
# inspector = ["bevy-inspector-egui"]

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1


[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
# opt-level = "z"
#lto = true
strip = true
lto = "thin"

[profile.release-with-debuginfo]
inherits = "release"
debug = true
strip = false
