[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    # "x86_64-pc-windows-msvc",
]

[bans]
# multiple-versions = "deny"

[licenses]
version = 2
allow = [
  "LGPL-3.0",
  "Apache-2.0",
  "MIT",
  "MIT-0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "Zlib",
  "ISC",
  "CC0-1.0",
  "BSL-1.0",
  "LicenseRef-UFL-1.0",
  "OFL-1.1",
  "Unicode-DFS-2016"
]
