name: Build binaries

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-24.04", "macos-12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: |
          cargo --locked build --release

      - uses: actions/upload-artifact@v4
        with:
          name: corroscope-${{ matrix.os }}
          path: target/release/corroscope

